spring.application.name=vit-result-portal

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/vit_result_portal?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Jackson
spring.jackson.default-property-inclusion=non_null
